### PR TITLE
[BIG-238] Handle interval datatype in REST API BQ

### PR DESCRIPTION
**Pull request by tomasfejfar**
Jira: BIG-238
Connection PR: https://github.com/keboola/connection/pull/4871
SAPI PR: https://github.com/keboola/storage-api-php-client/pull/1278

---

### CODE REVIEW

**Comment by jirkasemmler** [comment]
@tomasfejfar ten stan mam vyreseny. vyclenim ho do solo PR

**Comment by jirkasemmler** [comment]
nebo jinak - mergnul jsem https://github.com/keboola/storage-backend/pull/130 . tak si rebasni. pak to muzeme vydat oboji

**Comment by romanbracinik** [comment]
👁️

**Review by romanbracinik — APPROVED** [review]
🙆‍♂️ ked to requirnes v connection tak pak kuknem na tie dalsie dva PR na SAPI a connection

**Pull request merged**
