### PR TITLE
BIG-155 try use preserveAsciiControlCharacters when loading

### PR DESCRIPTION
**Pull request by zajca**

### CODE REVIEW

**Comment by romanbracinik** [comment]
Cool tak to preslo https://github.com/keboola/storage-backend/actions/runs/6549041110/job/17786141537?pr=79 idem to rebasnut

**Comment by romanbracinik** [comment]
@zajca mozes na to pls kuknut, bez tej upravy to failuje, jak som pisal na slacku zistil som ze je tam trosku bug/neocakavane chovanie a zalezi kam tie options das.

**Comment by zajca** [comment]
Nice prošlo to. :heavy_check_mark:

**Review by romanbracinik — APPROVED** [review]
na zaklade 👍 od zajci davam approve

**Pull request merged**
